substitutions:
  _INSTANCE_CONNECTION_NAME: "gen-lang-client-0577225072:us-central1:example-instance"

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gen-lang-client-0577225072/call-room-backend', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gen-lang-client-0577225072/call-room-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'call-room-backend'
      - '--image'
      - 'gcr.io/gen-lang-client-0577225072/call-room-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - 'gen-lang-client-0577225072:us-central1:example-instance'

images:
  - 'gcr.io/gen-lang-client-0577225072/call-room-backend'
