substitutions:
  _INSTANCE_CONNECTION_NAME: "$_INSTANCE_CONNECTION_NAME"

# Add logging configuration
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/call-room-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/call-room-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'call-room-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/call-room-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/call-room-backend:$COMMIT_SHA'
